export { default as IncrementIcon } from './increment-icon'
export { default as DecrementIcon } from './decrement-icon'
export { default as CartIcon } from './cart-icon'
export {default as RemoveItemIcon} from './remove-item-icon'
export {default as CarbonTreeIcon} from './carbon-tree-icon'
// export {default as } from ''
